version: '3.8'

services:
  backend:
    build: ./backend-tictactoe
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/tictactoe

  frontend:
    build: ./frontend-tictactoe
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
